 const monasteries = [
                // --- North Sikkim Monasteries (55 Entries) ---
                { id: 'phodong', name: "Phodong Monastery", lat: 27.429396, lng: 88.618610, district: "North Sikkim", description: "An important monastery of the Kagyupa sect.", attractions: [] },
                { id: 'phensang', name: "Phensang Monastery", lat: 27.4043, lng: 88.5913, district: "North Sikkim", description: "Known for its annual festival of sacred dances.", attractions: [] },
                { id: 'labrang', name: "Labrang Monastery", lat: 27.4530, lng: 88.6102, district: "North Sikkim", description: "A unique monastery of the Nyingmapa sect.", attractions: [] },
                { id: 'chungthang', name: "Chungthang Monastery", lat: 27.6075, lng: 88.6433, district: "North Sikkim", description: "A sacred site with a rock believed to bear Guru Padmasambhava's footprint.", attractions: [] },
                { id: 'lachen', name: "Lachen Monastery", lat: 27.7161, lng: 88.5574, district: "North Sikkim", description: "Offers stunning views of the surrounding Himalayan peaks.", attractions: [] },
                { id: 'lachung', name: "Lachung Monastery", lat: 27.6896, lng: 88.7431, district: "North Sikkim", description: "A vibrant monastery in the picturesque Lachung Valley.", attractions: [] },
                { id: 'thangu', name: "Thangu Monastery", lat: 27.8760, lng: 88.5300, district: "North Sikkim", description: "Located in the high-altitude Thangu Valley.", attractions: [] },
                { id: 'singik', name: "Singik Monastery", lat: 27.5167, lng: 88.5750, district: "North Sikkim", description: "Offers panoramic views of Mt. Kanchenjunga.", attractions: [] },
                { id: 'mangan', name: "Mangan Monastery", lat: 27.5000, lng: 88.5333, district: "North Sikkim", description: "The main monastery in the district headquarters.", attractions: [] },
                { id: 'tingchim', name: "Tingchim Monastery", lat: 27.4833, lng: 88.5500, district: "North Sikkim", description: "A quiet and serene monastery.", attractions: [] },
                { id: 'lingthem', name: "Lingthem Monastery", lat: 27.5500, lng: 88.6500, district: "North Sikkim", description: "Overlooks the confluence of two rivers.", attractions: [] },
                { id: 'hee-gyathang', name: "Hee-Gyathang Monastery", lat: 27.5333, lng: 88.6000, district: "North Sikkim", description: "An important place of worship for the local community.", attractions: [] },
                { id: 'kabi', name: "Kabi Monastery", lat: 27.4500, lng: 88.6167, district: "North Sikkim", description: "Site of the historic 'blood brotherhood' treaty.", attractions: [] },
                { id: 'talphung', name: "Talphung Monastery", lat: 27.5667, lng: 88.5833, district: "North Sikkim", description: "A lesser-known gem with rich history.", attractions: [] },
                { id: 'ringyim', name: "Ringyim Monastery", lat: 27.5186, lng: 88.5432, district: "North Sikkim", description: "Features beautiful murals and thangkas.", attractions: [] },
                { id: 'naga', name: "Naga Monastery", lat: 27.4667, lng: 88.5167, district: "North Sikkim", description: "Located near the village of Naga.", attractions: [] },
                { id: 'toong', name: "Toong Monastery", lat: 27.5833, lng: 88.6667, district: "North Sikkim", description: "A small monastery serving the Toong village.", attractions: [] },
                { id: 'shipgyer', name: "Shipgyer Monastery", lat: 27.6333, lng: 88.7167, district: "North Sikkim", description: "Located on the way to Lachung.", attractions: [] },
                { id: 'tsum', name: "Tsum Monastery", lat: 27.8000, lng: 88.7500, district: "North Sikkim", description: "A remote monastery in the high mountains.", attractions: [] },
                { id: 'namgyal-tsemo', name: "Namgyal Tsemo Monastery", lat: 27.7500, lng: 88.6000, district: "North Sikkim", description: "Perched high on a ridge.", attractions: [] },
                { id: 'dzongu', name: "Dzongu Monastery", lat: 27.5550, lng: 88.5050, district: "North Sikkim", description: "Located in the Lepcha reserve of Dzongu.", attractions: [] },
                { id: 'sakya-lachen', name: "Sakya Monastery of Lachen", lat: 27.7200, lng: 88.5600, district: "North Sikkim", description: "Follows the Sakya tradition of Tibetan Buddhism.", attractions: [] },
                { id: 'chaten', name: "Chaten Monastery", lat: 27.7833, lng: 88.5000, district: "North Sikkim", description: "A small gompa near the Indo-Tibetan border.", attractions: [] },
                { id: 'kalep', name: "Kalep Monastery", lat: 27.4333, lng: 88.5000, district: "North Sikkim", description: "A community monastery in a serene setting.", attractions: [] },
                { id: 'lingko', name: "Lingko Monastery", lat: 27.65, lng: 88.6, district: "North Sikkim", description: "A remote high-altitude monastery.", attractions: [] },
                { id: 'zadong', name: "Zadong Monastery", lat: 27.9, lng: 88.5, district: "North Sikkim", description: "Offers spectacular mountain vistas.", attractions: [] },
                { id: 'pentok', name: "Pentok Monastery", lat: 27.4, lng: 88.55, district: "North Sikkim", description: "A place of quiet contemplation.", attractions: [] },
                { id: 'muguthang', name: "Muguthang Gompa", lat: 27.95, lng: 88.6, district: "North Sikkim", description: "One of the highest monasteries in the region.", attractions: [] },
                { id: 'giwong', name: "Giwong Gompa", lat: 27.85, lng: 88.7, district: "North Sikkim", description: "A historic and culturally significant site.", attractions: [] },
                { id: 'tetso', name: "Tetso Monastery", lat: 27.6, lng: 88.58, district: "North Sikkim", description: "Known for its collection of ancient texts.", attractions: [] },
                { id: 'sakyong', name: "Sakyong Monastery", lat: 27.58, lng: 88.5, district: "North Sikkim", description: "An important center for Buddhist philosophy.", attractions: [] },
                { id: 'pothing', name: "Pothing Monastery", lat: 27.48, lng: 88.62, district: "North Sikkim", description: "A peaceful retreat for monks and visitors.", attractions: [] },
                { id: 'rang-rang', name: "Rang-Rang Monastery", lat: 27.46, lng: 88.58, district: "North Sikkim", description: "Features unique architectural elements.", attractions: [] },
                { id: 'namok', name: "Namok Monastery", lat: 27.44, lng: 88.56, district: "North Sikkim", description: "A center for local religious festivals.", attractions: [] },
                { id: 'singtam', name: "Singtam Gompa", lat: 27.49, lng: 88.51, district: "North Sikkim", description: "A monastery serving the local Singtam area.", attractions: [] },
                { id: 'barfok', name: "Barfok Monastery", lat: 27.62, lng: 88.68, district: "North Sikkim", description: "Known for its serene and isolated location.", attractions: [] },
                { id: 'zema', name: "Zema Monastery", lat: 27.82, lng: 88.65, district: "North Sikkim", description: "A gateway to the high-altitude Zema valley.", attractions: [] },
                { id: 'talam', name: "Talam Monastery", lat: 27.7, lng: 88.7, district: "North Sikkim", description: "A small but spiritually significant gompa.", attractions: [] },
                { id: 'singring', name: "Singring Monastery", lat: 27.67, lng: 88.55, district: "North Sikkim", description: "Holds a collection of rare Buddhist artifacts.", attractions: [] },
                { id: 'bey', name: "Bey Monastery", lat: 27.77, lng: 88.77, district: "North Sikkim", description: "Located in a hidden valley or 'beyul'.", attractions: [] },
                { id: 'yakthang', name: "Yakthang Monastery", lat: 27.73, lng: 88.63, district: "North Sikkim", description: "Surrounded by pastures for yaks.", attractions: [] },
                { id: 'talung', name: "Talung Monastery", lat: 27.64, lng: 88.45, district: "North Sikkim", description: "Guards the entrance to the Talung valley.", attractions: [] },
                { id: 'pakshep', name: "Pakshep Monastery", lat: 27.59, lng: 88.48, district: "North Sikkim", description: "A repository of local history and culture.", attractions: [] },
                { id: 'khecheopalri-north', name: "North Khecheopalri Gompa", lat: 27.66, lng: 88.33, district: "North Sikkim", description: "A monastery near a sacred, wish-fulfilling lake.", attractions: [] },
                { id: 'kay-monastery', name: "Kay Monastery", lat: 27.5, lng: 88.68, district: "North Sikkim", description: "An important Nyingma monastery.", attractions: [] },
                { id: 'nam-nagar', name: "Nam-Nagar Monastery", lat: 27.47, lng: 88.65, district: "North Sikkim", description: "A modern monastery with traditional architecture.", attractions: [] },
                { id: 'phamtam', name: "Phamtam Monastery", lat: 27.54, lng: 88.62, district: "North Sikkim", description: "Known for its butter lamp offerings.", attractions: [] },
                { id: 'tsungthang', name: "Tsungthang Monastery", lat: 27.61, lng: 88.65, district: "North Sikkim", description: "An alternate name for the Chungthang holy site.", attractions: [] },
                { id: 'gurudongmar', name: "Gurudongmar Gompa", lat: 27.98, lng: 88.7, district: "North Sikkim", description: "A small temple near the sacred Gurudongmar Lake.", attractions: [] },
                { id: 'chola-mu', name: "Chola Mu Monastery", lat: 28.05, lng: 88.75, district: "North Sikkim", description: "A remote site near the Tibetan plateau.", attractions: [] },
                { id: 'chulung', name: "Chulung Monastery", lat: 27.88, lng: 88.6, district: "North Sikkim", description: "A monastery frequented by yak herders.", attractions: [] },
                { id: 'tholung', name: "Tholung Monastery", lat: 27.6, lng: 88.4, district: "North Sikkim", description: "A remote monastery housing precious artifacts.", attractions: [] },
                { id: 'bayul-demazong', name: "Bayul Demazong", lat: 27.7, lng: 88.4, district: "North Sikkim", description: "A sacred hidden land and pilgrimage site.", attractions: [] },
                { id: 'kyeshong', name: "Kyeshong Monastery", lat: 27.8, lng: 88.45, district: "North Sikkim", description: "Located in a valley of medicinal herbs.", attractions: [] },
                { id: 'lhakhang', name: "Lhakhang Monastery", lat: 27.9, lng: 88.3, district: "North Sikkim", description: "A high-altitude temple of worship.", attractions: [] },

                // --- West Sikkim Monasteries (30 Entries) ---
                { id: 'pemayangtse', name: "Pemayangtse Monastery", lat: 27.301550, lng: 88.256884, district: "West Sikkim", description: "Famed for its intricate wooden sculptures.",
                    attractions: [
                        { name: "Rabdentse Ruins", lat: 27.3050, lng: 88.2650 },
                        { name: "Pelling Skywalk", lat: 27.2935, lng: 88.2452 }
                    ]
                },
                { id: 'tashiding', name: "Tashiding Monastery", lat: 27.271318, lng: 88.286164, district: "West Sikkim", description: "Considered the spiritual center of Sikkim.", attractions: [] },
                { id: 'dubdi', name: "Dubdi Monastery", lat: 27.375681, lng: 88.225586, district: "West Sikkim", description: "Often called the 'Hermit's Cell', the oldest in Sikkim.", attractions: [] },
                { id: 'sanga-choeling', name: "Sanga Choeling Monastery", lat: 27.2950, lng: 88.2450, district: "West Sikkim", description: "The second oldest monastery in Sikkim.", attractions: [] },
                { id: 'khecheopalri', name: "Khecheopalri Monastery", lat: 27.3710, lng: 88.2000, district: "West Sikkim", description: "Located by the sacred Khecheopalri Lake.", attractions: [] },
                { id: 'yuksom', name: "Yuksom Monastery", lat: 27.3667, lng: 88.2167, district: "West Sikkim", description: "Includes the coronation throne of the first Chogyal.", attractions: [] },
                { id: 'gyalshing', name: "Gyalshing Gompa", lat: 27.2833, lng: 88.2667, district: "West Sikkim", description: "The main monastery in the town of Gyalshing.", attractions: [] },
                { id: 'rinchenpong', name: "Rinchenpong Monastery", lat: 27.2333, lng: 88.2833, district: "West Sikkim", description: "Known for its statue of Ati Buddha.", attractions: [] },
                { id: 'pelling', name: "Pelling Monastery", lat: 27.3167, lng: 88.2333, district: "West Sikkim", description: "Offers stunning views of Kanchenjunga.", attractions: [] },
                { id: 'soreng', name: "Soreng Monastery", lat: 27.1667, lng: 88.2000, district: "West Sikkim", description: "A center of Buddhist learning in West Sikkim.", attractions: [] },
                { id: 'chakung', name: "Chakung Monastery", lat: 27.1500, lng: 88.2333, district: "West Sikkim", description: "A small monastery serving the Chakung area.", attractions: [] },
                { id: 'hiley', name: "Hiley Monastery", lat: 27.2667, lng: 88.1167, district: "West Sikkim", description: "A starting point for treks in the region.", attractions: [] },
                { id: 'uting', name: "Uting Monastery", lat: 27.4000, lng: 88.2500, district: "West Sikkim", description: "A remote and peaceful gompa.", attractions: [] },
                { id: 'yangtey', name: "Yangtey Monastery", lat: 27.3000, lng: 88.2833, district: "West Sikkim", description: "Overlooks the town of Pelling.", attractions: [] },
                { id: 'lingchom', name: "Lingchom Monastery", lat: 27.3500, lng: 88.3000, district: "West Sikkim", description: "A historic Nyingma monastery.", attractions: [] },
                { id: 'dentam', name: "Dentam Monastery", lat: 27.2500, lng: 88.1833, district: "West Sikkim", description: "Located in the beautiful Dentam valley.", attractions: [] },
                { id: 'hee-bermiok', name: "Hee-Bermiok Monastery", lat: 27.2167, lng: 88.2000, district: "West Sikkim", description: "A community monastery surrounded by nature.", attractions: [] },
                { id: 'kaluk', name: "Kaluk Monastery", lat: 27.2333, lng: 88.2500, district: "West Sikkim", description: "Known for its serene atmosphere.", attractions: [] },
                { id: 'patal', name: "Patal Monastery", lat: 27.32, lng: 88.15, district: "West Sikkim", description: "An ancient monastery of West Sikkim.", attractions: [] },
                { id: 'tingbung', name: "Tingbung Monastery", lat: 27.36, lng: 88.18, district: "West Sikkim", description: "A community monastery in Tingbung village.", attractions: [] },
                { id: 'sakyong-pentong', name: "Sakyong-Pentong Monastery", lat: 27.4, lng: 88.1, district: "West Sikkim", description: "Holds significant religious importance.", attractions: [] },
                { id: 'nampatam', name: "Nampatam Monastery", lat: 27.33, lng: 88.12, district: "West Sikkim", description: "A small gompa with beautiful surroundings.", attractions: [] },
                { id: 'zimchung', name: "Zimchung Monastery", lat: 27.42, lng: 88.14, district: "West Sikkim", description: "A remote monastery in the western hills.", attractions: [] },
                { id: 'tolung-west', name: "Tolung Monastery (West)", lat: 27.45, lng: 88.16, district: "West Sikkim", description: "A historic site preserving ancient relics.", attractions: [] },
                { id: 'rin-chen-po', name: "Rin-chen-po Monastery", lat: 27.2, lng: 88.19, district: "West Sikkim", description: "An important place for pilgrimage.", attractions: [] },
                { id: 'pakshek', name: "Pakshek Monastery", lat: 27.22, lng: 88.22, district: "West Sikkim", description: "A serene monastery away from tourist crowds.", attractions: [] },
                { id: 'thanggu-west', name: "Thanggu Monastery (West)", lat: 27.48, lng: 88.2, district: "West Sikkim", description: "High-altitude place of worship.", attractions: [] },
                { id: 'tashijong', name: "Tashijong Monastery", lat: 27.18, lng: 88.28, district: "West Sikkim", description: "A vibrant center for Tibetan arts.", attractions: [] },
                { id: 'singhik-gompa-west', name: "Singhik Viewpoint Gompa (West)", lat: 27.34, lng: 88.34, district: "West Sikkim", description: "Offers views of the Kanchenjunga range.", attractions: [] },
                { id: 'changthang-west', name: "Changthang Monastery (West)", lat: 27.5, lng: 88.25, district: "West Sikkim", description: "A monastery with a unique history.", attractions: [] },

                // --- South Sikkim Monasteries (50 Entries) ---
                { id: 'ralang', name: "Ralang Monastery", lat: 27.320476, lng: 88.384594, district: "South Sikkim", description: "A treasure of Buddhist art and paintings.", attractions: [] },
                { id: 'buddha-park', name: "Buddha Park of Ravangla", lat: 27.3105, lng: 88.3615, district: "South Sikkim", description: "Features a 130-foot high statue of the Buddha.", attractions: [] },
                { id: 'samdruptse', name: "Samdruptse Monastery", lat: 27.2286, lng: 88.2675, district: "South Sikkim", description: "Home to a giant statue of Guru Padmasambhava.", attractions: [] },
                { id: 'ngadak', name: "Ngadak Monastery", lat: 27.1758, lng: 88.2758, district: "South Sikkim", description: "One of the older monasteries, now in a peaceful, ruined state.", attractions: [] },
                { id: 'serdup-choling', name: "Serdup Choling Monastery", lat: 27.1700, lng: 88.3500, district: "South Sikkim", description: "Located in the heart of Namchi.", attractions: [] },
                { id: 'tendong', name: "Tendong Gumpa", lat: 27.2500, lng: 88.3500, district: "South Sikkim", description: "A small monastery situated on Tendong Hill.", attractions: [] },
                { id: 'sanga-choeling-namchi', name: "Sanga Choeling Monastery, Namchi", lat: 27.1650, lng: 88.3450, district: "South Sikkim", description: "Offers panoramic views of the surrounding hills.", attractions: [] },
                { id: 'sangling', name: "Sangling Monastery", lat: 27.2833, lng: 88.4000, district: "South Sikkim", description: "A beautiful monastery near Ravangla.", attractions: [] },
                { id: 'khyosphalri', name: "Khyosphalri Monastery", lat: 27.2167, lng: 88.3167, district: "South Sikkim", description: "Located near a sacred lake.", attractions: [] },
                { id: 'bermiok', name: "Bermiok Monastery", lat: 27.2000, lng: 88.3000, district: "South Sikkim", description: "A community monastery in a picturesque village.", attractions: [] },
                { id: 'mangbrue', name: "Mangbrue Gompa", lat: 27.2333, lng: 88.4167, district: "South Sikkim", description: "Known for its unique architectural style.", attractions: [] },
                { id: 'temi', name: "Temi Monastery", lat: 27.2345, lng: 88.4221, district: "South Sikkim", description: "Overlooks the famous Temi Tea Garden.", attractions: [] },
                { id: 'sikkim-university-gompa', name: "Sikkim University Gompa", lat: 27.2912, lng: 88.3334, district: "South Sikkim", description: "A modern gompa within the university campus.", attractions: [] },
                { id: 'namthang', name: "Namthang Monastery", lat: 27.1500, lng: 88.4000, district: "South Sikkim", description: "An important religious site for the local population.", attractions: [] },
                { id: 'kitam', name: "Kitam Monastery", lat: 27.1167, lng: 88.3333, district: "South Sikkim", description: "Located near the Kitam Bird Sanctuary.", attractions: [] },
                { id: 'perbing', name: "Perbing Monastery", lat: 27.2667, lng: 88.4333, district: "South Sikkim", description: "A small, peaceful monastery.", attractions: [] },
                { id: 'phur-tsa-chu', name: "Phur Tsa Chu Gompa", lat: 27.1333, lng: 88.2500, district: "South Sikkim", description: "Located near the hot springs.", attractions: [] },
                { id: 'jaubari', name: "Jaubari Monastery", lat: 27.1833, lng: 88.3833, district: "South Sikkim", description: "A serene monastery with views of Namchi.", attractions: [] },
                { id: 'palchen-choeling', name: "Palchen Choeling Monastery", lat: 27.1730, lng: 88.3550, district: "South Sikkim", description: "A large monastic complex in Namchi.", attractions: [] },
                { id: 'solophok', name: "Solophok Chardham", lat: 27.1338, lng: 88.3307, district: "South Sikkim", description: "A pilgrimage center with replicas of famous temples.", attractions: [] },
                { id: 'sadam', name: "Sadam Monastery", lat: 27.1521, lng: 88.3654, district: "South Sikkim", description: "A village monastery in South Sikkim.", attractions: [] },
                { id: 'assangthang', name: "Assangthang Monastery", lat: 27.1950, lng: 88.3450, district: "South Sikkim", description: "A small gompa with a peaceful atmosphere.", attractions: [] },
                { id: 'siktam', name: "Siktam Monastery", lat: 27.2150, lng: 88.3550, district: "South Sikkim", description: "Serves the local community of Siktam village.", attractions: [] },
                { id: 'lingmoo', name: "Lingmoo Monastery", lat: 27.2750, lng: 88.3250, district: "South Sikkim", description: "A historic monastery in rural South Sikkim.", attractions: [] },
                { id: 'yangyang', name: "Yangyang Monastery", lat: 27.2450, lng: 88.4550, district: "South Sikkim", description: "Known for its beautiful location.", attractions: [] },
                { id: 'wok', name: "Wok Monastery", lat: 27.2050, lng: 88.3650, district: "South Sikkim", description: "Overlooks the Wok valley.", attractions: [] },
                { id: 'tarethang', name: "Tarethang Monastery", lat: 27.1450, lng: 88.4250, district: "South Sikkim", description: "A small but important local monastery.", attractions: [] },
                { id: 'chalamthang', name: "Chalamthang Monastery", lat: 27.2250, lng: 88.4850, district: "South Sikkim", description: "A center for Buddhist teachings.", attractions: [] },
                { id: 'tarku', name: "Tarku Monastery", lat: 27.2550, lng: 88.4950, district: "South Sikkim", description: "Located in the town of Tarku.", attractions: [] },
                { id: 'pabong', name: "Pabong Monastery", lat: 27.2950, lng: 88.3950, district: "South Sikkim", description: "A historic site with ancient roots.", attractions: [] },
                { id: 'vok-monastery', name: "Vok Monastery", lat: 27.19, lng: 88.37, district: "South Sikkim", description: "A secluded monastery known for meditation.", attractions: [] },
                { id: 'ratey-pani', name: "Ratey Pani Monastery", lat: 27.16, lng: 88.41, district: "South Sikkim", description: "An important local gompa.", attractions: [] },
                { id: 'kewzing-south', name: "Kewzing Monastery (South)", lat: 27.28, lng: 88.3, district: "South Sikkim", description: "A well-preserved traditional monastery.", attractions: [] },
                { id: 'doling-gompa', name: "Doling Gompa", lat: 27.24, lng: 88.29, district: "South Sikkim", description: "Features a statue of the future Buddha.", attractions: [] },
                { id: 'borong', name: "Borong Monastery", lat: 27.26, lng: 88.41, district: "South Sikkim", description: "Famous for the annual Borong festival.", attractions: [] },
                { id: 'ben-monastery', name: "Ben Monastery", lat: 27.22, lng: 88.38, district: "South Sikkim", description: "A small, peaceful monastery near Ravangla.", attractions: [] },
                { id: 'sikip', name: "Sikip Monastery", lat: 27.1, lng: 88.3, district: "South Sikkim", description: "Located near the Rangeet river.", attractions: [] },
                { id: 'melli', name: "Melli Monastery", lat: 27.09, lng: 88.45, district: "South Sikkim", description: "A border town monastery.", attractions: [] },
                { id: 'jorethang', name: "Jorethang Monastery", lat: 27.14, lng: 88.28, district: "South Sikkim", description: "An important monastery in Jorethang town.", attractions: [] },
                { id: 'rabong', name: "Rabong Gompa", lat: 27.3, lng: 88.37, district: "South Sikkim", description: "A center for Buddhist studies.", attractions: [] },
                { id: 'maenam', name: "Maenam Monastery", lat: 27.29, lng: 88.36, district: "South Sikkim", description: "Located on the Maenam Hill.", attractions: [] },
                { id: 'chumbung', name: "Chumbung Monastery", lat: 27.2, lng: 88.25, district: "South Sikkim", description: "A historic site in South Sikkim.", attractions: [] },
                { id: 'gerethang', name: "Gerethang Monastery", lat: 27.15, lng: 88.3, district: "South Sikkim", description: "Offers views of the surrounding area.", attractions: [] },
                { id: 'ralong-palchen', name: "Ralong Palchen Choling", lat: 27.31, lng: 88.38, district: "South Sikkim", description: "The newer Ralang monastery.", attractions: [] },
                { id: 'tingmoo', name: "Tingmoo Monastery", lat: 27.27, lng: 88.31, district: "South Sikkim", description: "A village monastery with a strong community.", attractions: [] },
                { id: 'sangmo', name: "Sangmo Monastery", lat: 27.19, lng: 88.44, district: "South Sikkim", description: "A quiet place for meditation.", attractions: [] },
                { id: 'tokal', name: "Tokal Monastery", lat: 27.21, lng: 88.46, district: "South Sikkim", description: "A traditional Nyingma gompa.", attractions: [] },
                { id: 'mamley', name: "Mamley Gompa", lat: 27.18, lng: 88.36, district: "South Sikkim", description: "A small, historic monastery.", attractions: [] },
                { id: 'panchase', name: "Panchase Monastery", lat: 27.26, lng: 88.28, district: "South Sikkim", description: "Offers panoramic Himalayan views.", attractions: [] },
                { id: 'sosing', name: "Sosing Monastery", lat: 27.23, lng: 88.33, district: "South Sikkim", description: "A serene monastery in South Sikkim.", attractions: [] },

                // --- East Sikkim Monasteries (65 Entries) ---
                { id: 'rumtek', name: "Rumtek Monastery", lat: 27.291351, lng: 88.566373, district: "East Sikkim", description: "A sprawling complex, pivotal for Tibetan Buddhism.",
                    attractions: [
                        { name: "Jawaharlal Nehru Botanical Garden", lat: 27.2850, lng: 88.5680 },
                        { name: "Shanti Viewpoint", lat: 27.2981, lng: 88.5655 }
                    ]
                },
                { id: 'enchey', name: "Enchey Monastery", lat: 27.340915, lng: 88.618635, district: "East Sikkim", description: "Meaning 'the solitary temple', offering spectacular views.", attractions: [] },
                { id: 'lingdum', name: "Lingdum (Ranka) Monastery", lat: 27.329977, lng: 88.650849, district: "East Sikkim", description: "A picturesque complex serving as a training center.", attractions: [] },
                { id: 'gonjang', name: "Gonjang Monastery", lat: 27.3510, lng: 88.6110, district: "East Sikkim", description: "Offers panoramic views of Gangtok.", attractions: [] },
                { id: 'dodrul-chorten', name: "Do-Drul Chorten", lat: 27.3210, lng: 88.6080, district: "East Sikkim", description: "A stupa surrounded by 108 prayer wheels.", attractions: [] },
                { id: 'tsuklakhang', name: "Tsuklakhang Palace", lat: 27.3300, lng: 88.6167, district: "East Sikkim", description: "The former royal palace and monastery.", attractions: [] },
                { id: 'sa-ngor-chotshog', name: "Sa-Ngor-Chotshog Centre", lat: 27.3167, lng: 88.6000, district: "East Sikkim", description: "A Tibetan refugee monastic institution.", attractions: [] },
                { id: 'pabyuk', name: "Pabyuk Monastery", lat: 27.2833, lng: 88.6333, district: "East Sikkim", description: "A small, traditional monastery.", attractions: [] },
                { id: 'martam', name: "Martam Monastery", lat: 27.2500, lng: 88.5833, district: "East Sikkim", description: "Located in the serene Martam village.", attractions: [] },
                { id: 'aritar', name: "Aritar Gumpa", lat: 27.1833, lng: 88.6667, district: "East Sikkim", description: "One of the oldest monasteries in East Sikkim.", attractions: [] },
                { id: 'gnathang', name: "Gnathang Monastery", lat: 27.4167, lng: 88.8167, district: "East Sikkim", description: "Located in the high-altitude Gnathang Valley.", attractions: [] },
                { id: 'baba-mandir', name: "Baba Harbhajan Singh Mandir", lat: 27.3667, lng: 88.8500, district: "East Sikkim", description: "A shrine dedicated to an Indian army soldier.", attractions: [] },
                { id: 'phedang', name: "Phedang Monastery", lat: 27.3000, lng: 88.7000, district: "East Sikkim", description: "A small monastery on the route to Tsomgo Lake.", attractions: [] },
                { id: 'kyongnosla', name: "Kyongnosla Monastery", lat: 27.3500, lng: 88.7500, district: "East Sikkim", description: "Near the Kyongnosla Alpine Sanctuary.", attractions: [] },
                { id: 'tamzey', name: "Tamzey Monastery", lat: 27.2667, lng: 88.6667, district: "East Sikkim", description: "A quiet retreat in the East Sikkim countryside.", attractions: [] },
                { id: 'sichey', name: "Sichey Gumpa", lat: 27.3450, lng: 88.6250, district: "East Sikkim", description: "A small monastery located in the Sichey area of Gangtok.", attractions: [] },
                { id: 'karthok', name: "Karthok Monastery", lat: 27.2167, lng: 88.6000, district: "East Sikkim", description: "A beautiful monastery in Pakyong.", attractions: [] },
                { id: 'rongli', name: "Rongli Monastery", lat: 27.2000, lng: 88.7000, district: "East Sikkim", description: "An important monastery in the Rongli sub-division.", attractions: [] },
                { id: 'rhenock', name: "Rhenock Monastery", lat: 27.1667, lng: 88.6333, district: "East Sikkim", description: "The main monastery for the town of Rhenock.", attractions: [] },
                { id: 'rolep', name: "Rolep Monastery", lat: 27.2167, lng: 88.7333, district: "East Sikkim", description: "Located in the serene village of Rolep.", attractions: [] },
                { id: 'zigna', name: "Zigna Monastery", lat: 27.25, lng: 88.75, district: "East Sikkim", description: "A small monastery with a rich history.", attractions: [] },
                { id: 'sudung', name: "Sudung Monastery", lat: 27.28, lng: 88.78, district: "East Sikkim", description: "A remote gompa in the eastern hills.", attractions: [] },
                { id: 'lingtam', name: "Lingtam Monastery", lat: 27.22, lng: 88.79, district: "East Sikkim", description: "A monastery on the historic Silk Route.", attractions: [] },
                { id: 'zong', name: "Zong Monastery", lat: 27.3, lng: 88.8, district: "East Sikkim", description: "A high-altitude monastery with stunning views.", attractions: [] },
                { id: 'kupup', name: "Kupup Monastery", lat: 27.35, lng: 88.83, district: "East Sikkim", description: "Near the beautiful Kupup Lake.", attractions: [] },
                { id: 'sherathang', name: "Sherathang Monastery", lat: 27.38, lng: 88.85, district: "East Sikkim", description: "A monastery at a high-altitude trading post.", attractions: [] },
                { id: 'nathula', name: "Nathula Pass Shrine", lat: 27.385, lng: 88.831, district: "East Sikkim", description: "A shrine at the Indo-China border.", attractions: [] },
                { id: 'tsongmo', name: "Tsongmo Lake Shrine", lat: 27.37, lng: 88.76, district: "East Sikkim", description: "A small shrine by the sacred Changu Lake.", attractions: [] },
                { id: 'tumlong', name: "Tumlong Palace Ruins & Monastery", lat: 27.41, lng: 88.58, district: "East Sikkim", description: "The former capital of Sikkim.", attractions: [] },
                { id: 'khewzing-east', name: "Khewzing Monastery (East)", lat: 27.29, lng: 88.4, district: "East Sikkim", description: "A small community monastery.", attractions: [] },
                { id: 'tadong', name: "Tadong Monastery", lat: 27.31, lng: 88.59, district: "East Sikkim", description: "Located in the Tadong area of Gangtok.", attractions: [] },
                { id: 'burtuk', name: "Burtuk Monastery", lat: 27.36, lng: 88.61, district: "East Sikkim", description: "Overlooks the entire Gangtok town.", attractions: [] },
                { id: 'luing', name: "Luing Monastery", lat: 27.38, lng: 88.63, district: "East Sikkim", description: "A serene monastery above Gangtok.", attractions: [] },
                { id: 'assam-lingzey', name: "Assam Lingzey Monastery", lat: 27.27, lng: 88.68, district: "East Sikkim", description: "A monastery in the village of Assam Lingzey.", attractions: [] },
                { id: 'samsing', name: "Samsing Monastery", lat: 27.26, lng: 88.72, district: "East Sikkim", description: "A small gompa with a beautiful setting.", attractions: [] },
                { id: 'pakyong', name: "Pakyong Monastery", lat: 27.23, lng: 88.6, district: "East Sikkim", description: "The main monastery in Pakyong.", attractions: [] },
                { id: 'changey', name: "Changey Monastery", lat: 27.2, lng: 88.62, district: "East Sikkim", description: "A historic monastery in East Sikkim.", attractions: [] },
                { id: 'tintek', name: "Tintek Monastery", lat: 27.39, lng: 88.6, district: "East Sikkim", description: "Offers a viewpoint of the Teesta river.", attractions: [] },
                { id: 'salamthang', name: "Salamthang Monastery", lat: 27.2, lng: 88.55, district: "East Sikkim", description: "A community monastery.", attractions: [] },
                { id: 'tumin', name: "Tumin Monastery", lat: 27.35, lng: 88.55, district: "East Sikkim", description: "Located in the quiet Tumin village.", attractions: [] },
                { id: 'sang', name: "Sang Monastery", lat: 27.3, lng: 88.53, district: "East Sikkim", description: "A culturally rich monastery.", attractions: [] },
                { id: 'makha', name: "Makha Monastery", lat: 27.28, lng: 88.53, district: "East Sikkim", description: "An important religious center for the surrounding area.", attractions: [] },
                { id: 'sirwani', name: "Sirwani Monastery", lat: 27.26, lng: 88.56, district: "East Sikkim", description: "A serene and peaceful gompa.", attractions: [] },
                { id: 'chumthang-east', name: "Chumthang Monastery (East)", lat: 27.24, lng: 88.54, district: "East Sikkim", description: "A small, traditional monastery.", attractions: [] },
                { id: 'yumesamdong-shrine', name: "Yumesamdong Zero Point Shrine", lat: 27.9, lng: 88.8, district: "East Sikkim", description: "A high-altitude shrine.", attractions: [] },
                { id: 'katao-monastery', name: "Katao Monastery", lat: 27.8, lng: 88.78, district: "East Sikkim", description: "Located in a militarily sensitive area.", attractions: [] },
                { id: 'dzong-nag', name: "Dzong-nag Monastery", lat: 27.33, lng: 88.7, district: "East Sikkim", description: "A historic Nyingma site.", attractions: [] },
                { id: 'meyong', name: "Meyong Monastery", lat: 27.36, lng: 88.67, district: "East Sikkim", description: "A small community gompa.", attractions: [] },
                { id: 'senti', name: "Senti Monastery", lat: 27.31, lng: 88.68, district: "East Sikkim", description: "Offers views of the surrounding valleys.", attractions: [] },
                { id: 'ringdang', name: "Ringdang Monastery", lat: 27.29, lng: 88.72, district: "East Sikkim", description: "A local place of worship.", attractions: [] },
                { id: 'lingzya', name: "Lingzya Monastery", lat: 27.27, lng: 88.75, district: "East Sikkim", description: "A remote monastery in East Sikkim.", attractions: [] },
                { id: 'gnon', name: "Gnon Monastery", lat: 27.25, lng: 88.8, district: "East Sikkim", description: "A historic monastery.", attractions: [] },
                { id: 'thak-chang', name: "Thak-chang Monastery", lat: 27.22, lng: 88.82, district: "East Sikkim", description: "A serene and peaceful location.", attractions: [] },
                { id: 'pangthang', name: "Pangthang Monastery", lat: 27.35, lng: 88.63, district: "East Sikkim", description: "Located in the Pangthang area of Gangtok.", attractions: [] },
                { id: 'tathangchen', name: "Tathangchen Monastery", lat: 27.34, lng: 88.6, district: "East Sikkim", description: "A prominent monastery within Gangtok.", attractions: [] },
                { id: 'deorali', name: "Deorali Monastery", lat: 27.32, lng: 88.61, district: "East Sikkim", description: "Located near the Namgyal Institute of Tibetology.", attractions: [] },
                { id: 'dharma-chakra-centre', name: "Rumtek Dharma Chakra Centre", lat: 27.29, lng: 88.56, district: "East Sikkim", description: "The main seat of the Karma Kagyu lineage.", attractions: [] },
                { id: 'gangtok-gumpa', name: "Gangtok Gumpa", lat: 27.33, lng: 88.61, district: "East Sikkim", description: "A central monastery in the capital.", attractions: [] },
                { id: 'lingjey', name: "Lingjey Monastery", lat: 27.28, lng: 88.69, district: "East Sikkim", description: "A village monastery.", attractions: [] },
                { id: 'parbing', name: "Parbing Monastery", lat: 27.24, lng: 88.64, district: "East Sikkim", description: "A local religious center.", attractions: [] },
                { id: 'samdong', name: "Samdong Monastery", lat: 27.4, lng: 88.64, district: "East Sikkim", description: "A historic monastery in East Sikkim.", attractions: [] },
                { id: 'rakdong-tintek', name: "Rakdong-Tintek Monastery", lat: 27.39, lng: 88.62, district: "East Sikkim", description: "Serves the local communities.", attractions: [] },
                { id: 'khamdong', name: "Khamdong Monastery", lat: 27.27, lng: 88.58, district: "East Sikkim", description: "An important monastery in the Khamdong area.", attractions: [] },
                { id: 'nathu-gumpa', name: "Nathu-Gumpa Monastery", lat: 27.38, lng: 88.82, district: "East Sikkim", description: "A small monastery near Nathu La pass.", attractions: [] },
                { id: 'tseten-tashi', name: "Tseten Tashi Cave", lat: 27.36, lng: 88.59, district: "East Sikkim", description: "A sacred cave and pilgrimage site.", attractions: [] }
            ];