# Generated by Django 5.2.6 on 2025-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='monasteries/')),
                ('google_map_embed_url', models.URLField(help_text='Paste the Google Maps Embed URL')),
            ],
        ),
    ]
