# Generated by Django 5.2.6 on 2025-09-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monastery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monastery',
            name='google_map_embed_url',
            field=models.URLField(blank=True, help_text='Paste the Google Maps Embed URL', null=True),
        ),
        migrations.AlterField(
            model_name='monastery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='monasteries/'),
        ),
        migrations.AlterField(
            model_name='monastery',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
