# Generated by Django 5.2.6 on 2025-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_monastery_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monastery',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
