# Generated by Django 5.2.6 on 2025-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_monastery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monastery_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('district', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('attractions', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
